# Generated by Django 4.2.3 on 2023-07-04 06:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deparments",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Deparment",
                "verbose_name_plural": "Deparments",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("legal_document", models.CharField(max_length=100)),
                ("business_name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
            },
        ),
        migrations.CreateModel(
            name="UnitsOfMeasurement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Unit of measurement",
                "verbose_name_plural": "Units of measurement",
            },
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("existence", models.IntegerField(blank=True, null=True)),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "unit_of_measurement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contabilidad_dev.unitsofmeasurement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
            },
        ),
    ]
