# Generated by Django 4.2.3 on 2023-07-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contabilidad_dev", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deparments",
            options={"verbose_name": "Department", "verbose_name_plural": "Departments"},
        ),
        migrations.AddField(
            model_name="unitsofmeasurement",
            name="name",
            field=models.CharField(default="default", max_length=100),
            preserve_default=False,
        ),
    ]
