# Generated by Django 4.2.3 on 2023-08-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contabilidad_dev", "0002_alter_deparments_options_unitsofmeasurement_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entry_identifier", models.CharField(max_length=1000)),
                ("description", models.TextField()),
                ("inventory_type_identifier", models.CharField(max_length=1000)),
                ("account", models.CharField(max_length=1000)),
                (
                    "movement_type",
                    models.CharField(choices=[("DB", "Debit"), ("CR", "Credit")], default="DB", max_length=2),
                ),
                ("entry_date", models.DateField()),
                ("entry_amount", models.DecimalField(decimal_places=2, max_digits=1000)),
                ("status", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Accounting entry",
                "verbose_name_plural": "Accounting entries",
            },
        ),
    ]
