# Generated by Django 4.2.3 on 2023-08-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contabilidad_dev", "0005_accountingentry_cuentacr_accountingentry_cuentadb"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountingentry",
            name="cuenta_contable",
        ),
        migrations.RemoveField(
            model_name="accountingentry",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="accountingentry",
            name="fecha_registro",
        ),
        migrations.RemoveField(
            model_name="accountingentry",
            name="tipo_movimiento",
        ),
        migrations.AlterField(
            model_name="accountingentry",
            name="monto",
            field=models.IntegerField(),
        ),
    ]
